# Generated by Django 2.0.3 on 2018-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistep',
            name='apistep',
            field=models.CharField(max_length=64, null=True, verbose_name='测试步骤'),
        ),
    ]
